CREATE TABLE IF NOT EXISTS app (
    app_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    classroom_id BIGINT NOT NULL,
    app_name VARCHAR(255) NOT NULL,
    app_img VARCHAR(255) NOT NULL,
    delete_state BOOLEAN NOT NULL DEFAULT FALSE
);
