spring:
  application:
    name: padlock
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
  sql:
    init:
      mode: always

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

jwt:
  secret-key: ${SECRET_KEY}
  refresh-key: ${REFRESH_KEY}

app:
  fastapi:
    url: http://222.107.238.44:8001